import type { NextApiRequest, NextApiResponse } from 'next';
import { publicClient, walletClient, MACI_RLA_ABI, getAddresses } from '@/lib/server';
import * as path from 'path';
import * as fs from 'fs';

function getProofsDir(pollId: number | string): string {
  return path.resolve(process.cwd(), `../proofs-web/poll-${pollId}`);
}

function getCommitmentsFile(pollId: number | string): string {
  return path.join(getProofsDir(pollId), 'commitments.json');
}

/**
 * POST /api/coordinator/rla-commit
 * Reads commitments from commitments.json (generated by coordinator-commitments.ts),
 * then calls MaciRLA.commitResult().
 *
 * No proof files required — only circuit inputs and extracted commitments.
 */
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const cookie = req.headers.cookie || '';
  const authed = /(?:^|;\s*)coordinator_auth=true(?:;|$)/.test(cookie);
  if (!authed) {
    return res.status(401).json({ success: false, error: 'Unauthorized' });
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { pollId } = req.body;
    if (pollId === undefined) {
      return res.status(400).json({ success: false, error: 'pollId required' });
    }

    const { maciRla } = getAddresses();
    if (!maciRla) {
      return res.status(500).json({ success: false, error: 'MaciRLA address not configured' });
    }

    // Get correct poll address for this pollId
    const configPath = path.resolve(process.cwd(), '..', 'deploy-config.json');
    const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));

    let pollAddress: `0x${string}`;
    if (config.polls && config.polls[pollId.toString()]) {
      pollAddress = config.polls[pollId.toString()].pollAddress;
    } else if (pollId === 0 || pollId.toString() === config.pollId) {
      pollAddress = config.pollAddress;
    } else {
      return res.status(500).json({ success: false, error: `Poll ${pollId} configuration not found` });
    }

    const commitmentsFile = getCommitmentsFile(pollId);

    if (!fs.existsSync(commitmentsFile)) {
      return res.status(400).json({
        success: false,
        error: `commitments.json not found for Poll #${pollId}. Run Extract Commitments first.`,
        details: `Expected file: ${commitmentsFile}`,
      });
    }

    const commitmentsData = JSON.parse(fs.readFileSync(commitmentsFile, 'utf8'));
    const pmCommitments = commitmentsData.pmCommitments.map((c: string) => BigInt(c));
    const tvCommitments = commitmentsData.tvCommitments.map((c: string) => BigInt(c));
    const yesVotes = BigInt(commitmentsData.yesVotes);
    const noVotes = BigInt(commitmentsData.noVotes);

    // Check for suspicious 0 vs 0 result
    const { POLL_ABI } = await import('@/lib/server');
    const [, messages] = await publicClient.readContract({
      address: pollAddress,
      abi: POLL_ABI,
      functionName: 'numSignUpsAndMessages',
    } as any) as [bigint, bigint];

    if (messages > 1n && yesVotes === 0n && noVotes === 0n) {
      console.error('\n⚠️  WARNING: Committing 0 vs 0 result but poll has', messages.toString(), 'messages');
      console.error('   This likely indicates a coordinator key mismatch.');
      console.error('   Votes were encrypted with a different public key than the one being used for decryption.\n');

      return res.status(400).json({
        success: false,
        error: `Refusing to commit suspicious result: 0 vs 0 with ${messages} messages. Check coordinator key mismatch.`,
        details: {
          messages: messages.toString(),
          yesVotes: '0',
          noVotes: '0',
          hint: 'Votes may have been encrypted with wrong coordinator public key',
        },
      });
    }

    const stake = await publicClient.readContract({
      address: maciRla,
      abi: MACI_RLA_ABI,
      functionName: 'coordinatorStake',
    } as any);

    const hash = await walletClient.writeContract({
      address: maciRla,
      abi: MACI_RLA_ABI,
      functionName: 'commitResult',
      args: [pollAddress, pmCommitments, tvCommitments, yesVotes, noVotes],
      value: stake as bigint,
    } as any);

    await publicClient.waitForTransactionReceipt({ hash });

    const nextPollId = await publicClient.readContract({
      address: maciRla,
      abi: MACI_RLA_ABI,
      functionName: 'nextPollId',
    } as any);

    res.status(200).json({
      success: true,
      txHash: hash,
      rlaPollId: Number(nextPollId as bigint) - 1,
      pmBatches: pmCommitments.length - 1,
      tvBatches: tvCommitments.length - 1,
      yesVotes: yesVotes.toString(),
      noVotes: noVotes.toString(),
    });
  } catch (err: any) {
    console.error('rla-commit error:', err);
    res.status(500).json({
      success: false,
      error: 'Failed to commit result',
      details: err.message,
      suggestion: 'Check that commitments.json exists and wallet has sufficient ETH for stake',
    });
  }
}
